# Hexo Configuration

# Site
language: zh-TW

shortcut_icon: /images/avatar.jpg
favicon: /images/avatar.jpg
avatar: /images/avatar.jpg

# Theme
theme: resume
theme_config:
  robots: index,follow
  copyright: '[Copyright © 2021 Chai-Shi Chang](/)'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://iknowright.github.io/ccs-resume-docs
# url: http://127.0.0.1:4000/ccs-resume-docs
root: /ccs-resume-docs/
permalink: posts/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code

# Directory
source_dir: src
public_dir: public
skip_render: README.md
exclude: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '    '

index_generator:
  path: 'index'
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: 'YYYY-MM-DD dddd'
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname:

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes

exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true


import:
  meta:
  - '<meta name="msapplication-TileColor" content="#ffffff">'
  - '<meta name="msapplication-TileImage" content="/ccs-resume-docs/images/favicon/ms-icon-144x144.png">'
  - '<meta name="theme-color" content="#ffffff">'
  link:
  - '<link rel="apple-touch-icon" sizes="57x57" href="/ccs-resume-docs/images/favicon/apple-icon-57x57.png">'
  - '<link rel="apple-touch-icon" sizes="60x60" href="/ccs-resume-docs/images/favicon/apple-icon-60x60.png">'
  - '<link rel="apple-touch-icon" sizes="72x72" href="/ccs-resume-docs/images/favicon/apple-icon-72x72.png">'
  - '<link rel="apple-touch-icon" sizes="76x76" href="/ccs-resume-docs/images/favicon/apple-icon-76x76.png">'
  - '<link rel="apple-touch-icon" sizes="114x114" href="/ccs-resume-docs/images/favicon/apple-icon-114x114.png">'
  - '<link rel="apple-touch-icon" sizes="120x120" href="/ccs-resume-docs/images/favicon/apple-icon-120x120.png">'
  - '<link rel="apple-touch-icon" sizes="144x144" href="/ccs-resume-docs/images/favicon/apple-icon-144x144.png">'
  - '<link rel="apple-touch-icon" sizes="152x152" href="/ccs-resume-docs/images/favicon/apple-icon-152x152.png">'
  - '<link rel="apple-touch-icon" sizes="180x180" href="/ccs-resume-docs/images/favicon/apple-icon-180x180.png">'
  - '<link rel="icon" type="image/png" sizes="192x192"  href="/ccs-resume-docs/images/favicon/android-icon-192x192.png">'
  - '<link rel="icon" type="image/png" sizes="32x32" href="/ccs-resume-docs/images/favicon/favicon-32x32.png">'
  - '<link rel="icon" type="image/png" sizes="96x96" href="/ccs-resume-docs/images/favicon/favicon-96x96.png">'
  - '<link rel="icon" type="image/png" sizes="16x16" href="/ccs-resume-docs/images/favicon/favicon-16x16.png">'
  - '<link rel="manifest" href="/manifest.json">'

nofollow:
  enable: true

# npm i hexo-neat
neat_enable: true

deploy:
  type: git
  repo: git@github.com:iknowright/ccs-resume-docs.git
  branch: gh-pages
  message: update resume

feed:
  type: atom
  path: atom.xml
  limit: 20
